### ISSUE TITLE
getFlag returns number instead of image

### ISSUE THREAD

**Issue by preto89** [thegamenicorus/react-native-phone-input#109]
getFlag always returns a number
how am i supposed to use that as an image?

`console.log(this.input.getFlag("gb"))`
`returns 79`

<Image source={79} ????? how does this work

**Comment by jaydenwindle** [comment]
Hey @preto89! Since the flag images are loaded using `require` in [`resources/flags/index.js`](https://github.com/thegamenicorus/react-native-phone-input/blob/9db8aee3b5ee04f9a271bccac0541913b48d97fd/lib/resources/flags/index.js), the `getFlag` function returns the asset reference (which is a number). This is the same value that is returned by `require`ing the image directly. 

```javascript
this.input.getFlag("gb") === require('react-native-phone-input/lib/resources/flags/images/gb.png')
```

You should be able to pass this value directly to `Image.source`, or you can use [`resolveAssetSource`](https://facebook.github.io/react-native/docs/image#resolveassetsource) if you need to access the `uri`, `width`, or `height` of the image. You can read more about how RN handles images in the [docs](https://facebook.github.io/react-native/docs/images#static-image-resources).
