### ISSUE TITLE
Placeholder TextInput

### ISSUE THREAD

**Issue by mohamedtijani** [thegamenicorus/react-native-phone-input#13]
I can not add a placeholder for the TextInput

**Comment by thegamenicorus** [comment]
Hi @mohamedtijani 

You can do

```
<PhoneInput ref="phone" textProps={{ placeholder: "1122" }} />
```

for add placeholder to the input

**Comment by Ikiugu** [comment]
Hi @thegamenicorus I still cant add a placeholder. Even when copying the above code. It does not display.
Here is my code: ` <PhoneInput
            ref="phone"
            onPressFlag={this.onPressFlag}
            textProps={{ placeholder: '1122' }}
          />`

**Comment by ashutoshshubam** [comment]
hi @Ikiugu did you get that hoe to use placeholder...tell me how use it

**Comment by Ikiugu** [comment]
Hi @ashutoshshubam unfortunately I did not get how to use this

**Comment by vksgautam1** [comment]
still same issue with no luck

**Comment by ckOfor** [comment]
Same issue

**Comment by ashutosh-patel95** [comment]
Hi @ikiugu use react-native-country-picker-modal
it has placeholder

**Comment by emjayschoen** [comment]
The problem (for me at least) was actually that the default initialCountry value ('us') was setting the value of the input to "+1", so the non-empty value meant the placeholder wasn't shown. If I backspaced to delete the "+1", the placeholder appeared as I set it. 

The novel solution is setting initialCountry code to null, which shows the placeholder but means users will always have to manually select a country code. 

A better solution would allow setting both an initial country code and a placeholder. If the placeholder is set, show the initial country's flag along with the placeholder instead of the actual "+1" value, then add the "+1" once the user focuses on the input for the first time.

@thegamenicorus Thoughts on whether this could be added?

**Comment by shimatai** [comment]
@emjayschoen to achieve a solution that supports a initial country code **and** a placeholder, you should do this:

Edit index.js of react-native-phone-input and add the following method:

`componentDidMount() {
    if (this.props.textProps.placeholder) {
        this.setState({ formattedNumber: this.state.formattedNumber + ' ' + this.props.textProps.placeholder});
    }
}`

Then you should add a `onFocus` on `<TextComponent ... />` (line 189 of version 0.2.1):

`onFocus={() => {
    this.setState({ formattedNumber: formattedNumber.replace(/[^0-9+-]/g, '') });
    }}`

PhoneInput field only allows the user to type numbers (because it uses keyboardType = "phone-pad"), so when user focus on input field, it removes all non-phone digits (0-9 +-) of placeholder.

Then all you got to do is to declare a placeholder in `<PhoneInput .../>`, like this:

`<PhoneInput
textProps={{ placeholder: 'Cellphone', placeholderTextColor: '#c0c0c0' }}
initialCountry={"us"}
/>`

The result will be:
"+1 Cellphone" (for US)
When user focus the input field, it will remain "+1" and the user types the cellphone number.

**Comment by TopGuru315** [comment]
It is not working on my side
Can you tell me the details of it?

**Comment by shridhar-s** [comment]
@thegamenicorus Can this fix be implemented and the package updated asap?
