### ISSUE TITLE
Cannot read property 'isValidNumber' of undefined  and undefined is not an object evaluating this.phone.isValidNo

### ISSUE THREAD

**Issue by mdshadman** [thegamenicorus/react-native-phone-input#131]
<PhoneInput
                ref={ref => {
                    this.phone = ref;
                }}
                style={styles.textInput}
                keyboardType="phone-pad"
                flagStyle={styles.flag}
                textStyle={styles.textinputStyle}
                initialCountry='in'
                placeholder={'70XXXXXXXX'}
                onPressConfirm={this.buttonPosition}
            />

In the above code this.phone is throwing undefined

**Comment by jaydenwindle** [comment]
Hey @mdshadman! Can you please attach a full code sample? Or even better, an expo snack that reproduces the issue? It's a little hard to tell what the problem is here from the info you've provided.

My guess is that you're trying to call `this.phone.isValidNumber` from somewhere where `this.phone` hasn't been set yet.

You can see an example of using a `PhoneInput` ref with a functional component and hooks here: https://snack.expo.io/@jaydenwindle/react-native-phone-input-ref-example
